# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cpr_monitor_pb2 as cpr__monitor__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cpr_monitor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CPRMonitorServiceStub(object):
    """==================== gRPC Service ====================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitializeSession = channel.unary_unary(
                '/cpr_monitor.v1.CPRMonitorService/InitializeSession',
                request_serializer=cpr__monitor__pb2.InitializeRequest.SerializeToString,
                response_deserializer=cpr__monitor__pb2.InitializeResponse.FromString,
                _registered_method=True)
        self.StartDetection = channel.unary_unary(
                '/cpr_monitor.v1.CPRMonitorService/StartDetection',
                request_serializer=cpr__monitor__pb2.StartDetectionRequest.SerializeToString,
                response_deserializer=cpr__monitor__pb2.StartDetectionResponse.FromString,
                _registered_method=True)
        self.StopDetection = channel.unary_unary(
                '/cpr_monitor.v1.CPRMonitorService/StopDetection',
                request_serializer=cpr__monitor__pb2.StopDetectionRequest.SerializeToString,
                response_deserializer=cpr__monitor__pb2.StopDetectionResponse.FromString,
                _registered_method=True)
        self.ProcessFrame = channel.unary_unary(
                '/cpr_monitor.v1.CPRMonitorService/ProcessFrame',
                request_serializer=cpr__monitor__pb2.ProcessFrameRequest.SerializeToString,
                response_deserializer=cpr__monitor__pb2.ProcessFrameResponse.FromString,
                _registered_method=True)
        self.GetMetrics = channel.unary_unary(
                '/cpr_monitor.v1.CPRMonitorService/GetMetrics',
                request_serializer=cpr__monitor__pb2.GetMetricsRequest.SerializeToString,
                response_deserializer=cpr__monitor__pb2.CPRMetrics.FromString,
                _registered_method=True)
        self.StreamMetrics = channel.unary_stream(
                '/cpr_monitor.v1.CPRMonitorService/StreamMetrics',
                request_serializer=cpr__monitor__pb2.StreamMetricsRequest.SerializeToString,
                response_deserializer=cpr__monitor__pb2.CPRMetrics.FromString,
                _registered_method=True)
        self.GetCoachingFeedback = channel.unary_unary(
                '/cpr_monitor.v1.CPRMonitorService/GetCoachingFeedback',
                request_serializer=cpr__monitor__pb2.GetCoachingFeedbackRequest.SerializeToString,
                response_deserializer=cpr__monitor__pb2.CoachingFeedback.FromString,
                _registered_method=True)
        self.LoadModel = channel.unary_unary(
                '/cpr_monitor.v1.CPRMonitorService/LoadModel',
                request_serializer=cpr__monitor__pb2.LoadModelRequest.SerializeToString,
                response_deserializer=cpr__monitor__pb2.LoadModelResponse.FromString,
                _registered_method=True)
        self.DetectPoses = channel.unary_unary(
                '/cpr_monitor.v1.CPRMonitorService/DetectPoses',
                request_serializer=cpr__monitor__pb2.DetectPosesRequest.SerializeToString,
                response_deserializer=cpr__monitor__pb2.DetectPosesResponse.FromString,
                _registered_method=True)
        self.StartMetronome = channel.unary_unary(
                '/cpr_monitor.v1.CPRMonitorService/StartMetronome',
                request_serializer=cpr__monitor__pb2.StartMetronomeRequest.SerializeToString,
                response_deserializer=cpr__monitor__pb2.StartMetronomeResponse.FromString,
                _registered_method=True)
        self.StopMetronome = channel.unary_unary(
                '/cpr_monitor.v1.CPRMonitorService/StopMetronome',
                request_serializer=cpr__monitor__pb2.StopMetronomeRequest.SerializeToString,
                response_deserializer=cpr__monitor__pb2.StopMetronomeResponse.FromString,
                _registered_method=True)
        self.StartCamera = channel.unary_unary(
                '/cpr_monitor.v1.CPRMonitorService/StartCamera',
                request_serializer=cpr__monitor__pb2.StartCameraRequest.SerializeToString,
                response_deserializer=cpr__monitor__pb2.StartCameraResponse.FromString,
                _registered_method=True)
        self.StopCamera = channel.unary_unary(
                '/cpr_monitor.v1.CPRMonitorService/StopCamera',
                request_serializer=cpr__monitor__pb2.StopCameraRequest.SerializeToString,
                response_deserializer=cpr__monitor__pb2.StopCameraResponse.FromString,
                _registered_method=True)
        self.StreamFrames = channel.stream_stream(
                '/cpr_monitor.v1.CPRMonitorService/StreamFrames',
                request_serializer=cpr__monitor__pb2.ProcessFrameRequest.SerializeToString,
                response_deserializer=cpr__monitor__pb2.ProcessFrameResponse.FromString,
                _registered_method=True)


class CPRMonitorServiceServicer(object):
    """==================== gRPC Service ====================

    """

    def InitializeSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartDetection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopDetection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCoachingFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectPoses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartMetronome(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopMetronome(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartCamera(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopCamera(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamFrames(self, request_iterator, context):
        """Bidirectional streaming for real-time CPR monitoring
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CPRMonitorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitializeSession': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeSession,
                    request_deserializer=cpr__monitor__pb2.InitializeRequest.FromString,
                    response_serializer=cpr__monitor__pb2.InitializeResponse.SerializeToString,
            ),
            'StartDetection': grpc.unary_unary_rpc_method_handler(
                    servicer.StartDetection,
                    request_deserializer=cpr__monitor__pb2.StartDetectionRequest.FromString,
                    response_serializer=cpr__monitor__pb2.StartDetectionResponse.SerializeToString,
            ),
            'StopDetection': grpc.unary_unary_rpc_method_handler(
                    servicer.StopDetection,
                    request_deserializer=cpr__monitor__pb2.StopDetectionRequest.FromString,
                    response_serializer=cpr__monitor__pb2.StopDetectionResponse.SerializeToString,
            ),
            'ProcessFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessFrame,
                    request_deserializer=cpr__monitor__pb2.ProcessFrameRequest.FromString,
                    response_serializer=cpr__monitor__pb2.ProcessFrameResponse.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=cpr__monitor__pb2.GetMetricsRequest.FromString,
                    response_serializer=cpr__monitor__pb2.CPRMetrics.SerializeToString,
            ),
            'StreamMetrics': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMetrics,
                    request_deserializer=cpr__monitor__pb2.StreamMetricsRequest.FromString,
                    response_serializer=cpr__monitor__pb2.CPRMetrics.SerializeToString,
            ),
            'GetCoachingFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCoachingFeedback,
                    request_deserializer=cpr__monitor__pb2.GetCoachingFeedbackRequest.FromString,
                    response_serializer=cpr__monitor__pb2.CoachingFeedback.SerializeToString,
            ),
            'LoadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=cpr__monitor__pb2.LoadModelRequest.FromString,
                    response_serializer=cpr__monitor__pb2.LoadModelResponse.SerializeToString,
            ),
            'DetectPoses': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectPoses,
                    request_deserializer=cpr__monitor__pb2.DetectPosesRequest.FromString,
                    response_serializer=cpr__monitor__pb2.DetectPosesResponse.SerializeToString,
            ),
            'StartMetronome': grpc.unary_unary_rpc_method_handler(
                    servicer.StartMetronome,
                    request_deserializer=cpr__monitor__pb2.StartMetronomeRequest.FromString,
                    response_serializer=cpr__monitor__pb2.StartMetronomeResponse.SerializeToString,
            ),
            'StopMetronome': grpc.unary_unary_rpc_method_handler(
                    servicer.StopMetronome,
                    request_deserializer=cpr__monitor__pb2.StopMetronomeRequest.FromString,
                    response_serializer=cpr__monitor__pb2.StopMetronomeResponse.SerializeToString,
            ),
            'StartCamera': grpc.unary_unary_rpc_method_handler(
                    servicer.StartCamera,
                    request_deserializer=cpr__monitor__pb2.StartCameraRequest.FromString,
                    response_serializer=cpr__monitor__pb2.StartCameraResponse.SerializeToString,
            ),
            'StopCamera': grpc.unary_unary_rpc_method_handler(
                    servicer.StopCamera,
                    request_deserializer=cpr__monitor__pb2.StopCameraRequest.FromString,
                    response_serializer=cpr__monitor__pb2.StopCameraResponse.SerializeToString,
            ),
            'StreamFrames': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamFrames,
                    request_deserializer=cpr__monitor__pb2.ProcessFrameRequest.FromString,
                    response_serializer=cpr__monitor__pb2.ProcessFrameResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cpr_monitor.v1.CPRMonitorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cpr_monitor.v1.CPRMonitorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CPRMonitorService(object):
    """==================== gRPC Service ====================

    """

    @staticmethod
    def InitializeSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cpr_monitor.v1.CPRMonitorService/InitializeSession',
            cpr__monitor__pb2.InitializeRequest.SerializeToString,
            cpr__monitor__pb2.InitializeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartDetection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cpr_monitor.v1.CPRMonitorService/StartDetection',
            cpr__monitor__pb2.StartDetectionRequest.SerializeToString,
            cpr__monitor__pb2.StartDetectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopDetection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cpr_monitor.v1.CPRMonitorService/StopDetection',
            cpr__monitor__pb2.StopDetectionRequest.SerializeToString,
            cpr__monitor__pb2.StopDetectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cpr_monitor.v1.CPRMonitorService/ProcessFrame',
            cpr__monitor__pb2.ProcessFrameRequest.SerializeToString,
            cpr__monitor__pb2.ProcessFrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cpr_monitor.v1.CPRMonitorService/GetMetrics',
            cpr__monitor__pb2.GetMetricsRequest.SerializeToString,
            cpr__monitor__pb2.CPRMetrics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cpr_monitor.v1.CPRMonitorService/StreamMetrics',
            cpr__monitor__pb2.StreamMetricsRequest.SerializeToString,
            cpr__monitor__pb2.CPRMetrics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCoachingFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cpr_monitor.v1.CPRMonitorService/GetCoachingFeedback',
            cpr__monitor__pb2.GetCoachingFeedbackRequest.SerializeToString,
            cpr__monitor__pb2.CoachingFeedback.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cpr_monitor.v1.CPRMonitorService/LoadModel',
            cpr__monitor__pb2.LoadModelRequest.SerializeToString,
            cpr__monitor__pb2.LoadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectPoses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cpr_monitor.v1.CPRMonitorService/DetectPoses',
            cpr__monitor__pb2.DetectPosesRequest.SerializeToString,
            cpr__monitor__pb2.DetectPosesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartMetronome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cpr_monitor.v1.CPRMonitorService/StartMetronome',
            cpr__monitor__pb2.StartMetronomeRequest.SerializeToString,
            cpr__monitor__pb2.StartMetronomeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopMetronome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cpr_monitor.v1.CPRMonitorService/StopMetronome',
            cpr__monitor__pb2.StopMetronomeRequest.SerializeToString,
            cpr__monitor__pb2.StopMetronomeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartCamera(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cpr_monitor.v1.CPRMonitorService/StartCamera',
            cpr__monitor__pb2.StartCameraRequest.SerializeToString,
            cpr__monitor__pb2.StartCameraResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopCamera(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cpr_monitor.v1.CPRMonitorService/StopCamera',
            cpr__monitor__pb2.StopCameraRequest.SerializeToString,
            cpr__monitor__pb2.StopCameraResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamFrames(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/cpr_monitor.v1.CPRMonitorService/StreamFrames',
            cpr__monitor__pb2.ProcessFrameRequest.SerializeToString,
            cpr__monitor__pb2.ProcessFrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
